### ISSUE TITLE
User Testing Nov 12 - 2018 ( Prototype )

### ISSUE THREAD

**Issue by RamyAlshurafa** [yalla-coop/connect5#17]
# User testing template

## Introduction

[Link to prototype](https://www.figma.com/proto/FSYdqP87hx39PwGA74OhkKmu/Connect-5?node-id=90%3A1&scaling=scale-down&redirected=1)

Thanks for helping us today. Just so you know, some of my team will be observing the session today, they're viewing the screen on our testing device and can hear your voice, so won't be a distraction. We are Founders and Coders alumni, We are the developers on the application, the application we're working on is a platform for Connect 5 trainers. The initial MVP will help trainers get feedback from the people who attend their training sessions and immediately see this feedback across every session. 

## Kick Off Questions:
May I ask you a few initial questions about yourself?

- What is your occupation?
- Do you use web applications (websites?) often?
- How do you currently get feedback from your training session participants?
- How do you currently report the impact of your training sessions to the setting you work in?

## Explanation

I'd like to show you the application first. [Please go to this link](https://www.figma.com/proto/FSYdqP87hx39PwGA74OhkKmu/Connect-5?node-id=90%3A1&scaling=scale-down&redirected=1)

This is the home page. I'm going to give you a few tasks to do from this page. It's a very free exercise so there are no right or wrong ways of doing things, this is not about you getting something wrong or right, we're looking to learn about the application. So that we know how you're finding it, we want you to talk aloud whatever you're thinking. So as you explore it, tell us anything that comes into your mind.

## Tasks

- ### Task 1

  - [ ] To start off please can you register on the app to get to your dashboard.

- ### Task 2

   - [ ] Great. Now can you please visit the session held on the 3rd November and find out what your survey responders found most useful frpom that session's training.

- ### Task 3

   - [ ] Please can you see the their individual survey response you have received for this session.

- ### Task 4

  - [ ] Now we would like you to view a summary of the results across all your sessions and see the feedback from your participants to the questions 'how important is it for you to support somebody with their mental health and wellbeing'

- ### Task 5

  - [ ] Please can you now add a new training session that you have coming up. 

 - ### Task 6

   

   - [ ] Great please finally delete the session of the 3rd November

## Follow Up Questions

-  How did you find using the application?
-  Did you have any other observations that you’d like to share?
-  Knowing what the platform is looking to do, is there anything else you would want to make you use it?
-  Have you used any similar platforms or applications before?
-  Do you have any further questions for us?

## Thanks!

Amazing! That’s everything now. Thanks so much for the help you’ve given us.

# Feedback Notes
< If exits >

**Comment by RamyAlshurafa** [comment]
# User Testing Session 1, Nov 12th, 09:10

## Trainer Name: **Charlie**

## Kick Off Questions:
#### What is your occupation?
* public health council (Swindon), connect5, c5 trainer (started recently)

#### Do you use web applications (websites?) often?
* yes, they do, mainly phone use

#### How do you currently get feedback from your training session participants?
* Connect 5 trainers, direct FB in training, 
* problem cant see feedback from surveys
* problems with survey monkey access due to site restrictions hence survey issues
* validation problems regarding survey monkey
* paper surveys saver but intense in terms of workload
* hence high chances of using the app, if trainers could access feedback after training
* Charlie's responsibility is to make sure the monitoring process for trainers works (which is not the case due to work overload and systemic problems)
#### How do you currently report the impact of your training sessions to the setting you work in?
* rather unstructured, sometimes emails, sometimes direct during training, surveys

## Tasks

- ### Task 1

  - [ ] To start off please can you register on the app to get to your dashboard.

    - no issues.

- ### Task 2

  - [ ] Great. Now can you please visit the session held on the 3rd November and find out what your survey responders found most useful from that session's training.

   -  call it "your sessions" instead of "sessions" to make it clear that it's only the logged in users sessions
   -  Type of session is not clear enough
   -  back button (x) on modal not clear enough
   -  "back" button on session details necessary
   -  another button for pre-survey results
   -  copy link should maybe be called share
- ### Task 3

  - [ ] Please, can you see their individual survey response you have received for this session?
     - no issues here

- ### Task 4

   - [ ] Now we would like you to view a summary of the results across all your sessions and see the feedback from your participants to the questions 'how important is it for you to support somebody with their mental health and wellbeing'

      -  "Results" should be called "Your Results"
      - no problems in assuming that results would be average across all sessions

- ### Task 5

  - [ ] Please, can you now add a new training session that you have coming up? 

    - No of people attended and registered instead 


- ### Task 6

  - [ ] Great please finally delete the session of the 3rd November


## Follow Up Questions

 - [ ] How did you find using the application?

   -  really helpful

 - [ ] Knowing what the platform is looking to do, is there anything else you would want to make you use it?
   -  trainers admin challenge: need to download the certificate in pdf, change certificate from pdf to word to put in details of the attendee in and send it manually to the participant
   -  would be great to automate that aspect 
   -  booking: anyone can book via Eventbrite putting emails in, not visible to trainers, trainer dl list of names --> useful to create all-c5-admin-system 
   -  told to stop using Eventbrite next month
   -  manually sending out surveys to people that booked sessions, pre-survey quite challenging before people starting the course

## Feedback Notes

 -  Microsoft phones for internal trainer process
 - restrictions by council regarding some URLs 
 -  color sensitive if lots of text on the page 
 -  important to track the number of people initially registered vs actually attended vs people submitted the survey
 - unique trainee number complicated concept and part of the reason that surveys via survey monkey are not effective enough
 - monitor performance over various sessions is only possible via individual requests on a national level.
 - no way of being sure if people submitted surveys so based on trust rather than tech 
* **Data protection issue:** legitimate to store user data on any database that's not connected to the council? 
 - offers to test MVP along her trainers but needs about 2-week notice to get things rolling

**Comment by RamyAlshurafa** [comment]
# User Testing Session 2, Nov 12th, 10:10

## Trainer name: Mike

## Kick Off Questions:

- What is your occupation?
    - Connect 5 trainers, community dev and fundraising officer

- Do you use web applications (websites?) often?
    - yes

- How do you currently get feedback from your training session participants?
    - paper copy pre-post evaluation forms, there is face to face feedback required after training sessions, more general chat of how they can use outcomes later on
    - doesn't use survey monkey due to issues related to data

- How do you currently report the impact of your training sessions to the setting you work in?
    - a quick review of paper copies after each session to see if serious cases/ issues
    - between trainers, reporting back to c5 coordinator in person
    - trainers only got registered participant's names 
    - c5 takes on booking procedures before course, not trainers themselves

## Tasks

- ### Task 1

  - [ ] To start off please can you register on the app to get to your dashboard.
    * Username placeholder not clear enough, better full or first name
    * call to action at bottom of om login page with 2 ?? to much, only 1?

- ### Task 2

  - [ ] Great. Now can you please visit the session held on the 3rd November and find out what your survey responders found most useful from that session's training.
    * no issues regarding the flow
    * know what session someone attended is important but any further tracking details like ID not necessary --> if particular issues come up that are worth feeding back to Connect 5 coordinator, that might change, so on a higher level it should be possible to track back individual responses but a training/trainer level anonymous feedback is sufficient and essential
    * doesn't use ID anyway as this would harm the training essence


- ### Task 3

  - [ ] Please, can you see their individual survey response you have received for this session?
    - no issues here

- ### Task 4

  - [ ] Now we would like you to view a summary of the results across all your sessions and see the feedback from your participants to the questions 'how important is it for you to support somebody with their mental health and wellbeing'
    * process a bit more tricky, results might not be clear enough
    * results -> view survey results
    * c5 rating system: often people rate themselves quite high pre-course so there is little room for tracking improvement


- ### Task 5

  - [ ] Please, can you now add a new training session that you have coming up? 
    * no issues regarding the flow
    * maybe organization field (where will the session be delivered to in order to group sessions within certain entities such as councils) in add session 


## Follow Up Questions

- How did you find using the application?
    - really easy and simple to use

- Did you have any other observations that you’d like to share?
    - on landing page check capital S spelling
    - **additional tools and resources category** would be very useful to include links, apps...
    - would make a huge impact on our connect5 system which is currently still based on loads of paperwork and decentralized organization 

- Knowing what the platform is looking to do, is there anything else you would want to make you use it?
    - good to have a shareable link to display during the session
    - the pre-session survey usually sent out before but also sometimes during the first session

**Comment by RamyAlshurafa** [comment]
# User Testing Session 3, Nov 12th, 10:50

## Trainer name: Mandy

## Kick Off Questions:

**- What is your occupation?**

   - Connect 5 training coordinator (arranging bookings and sent out details) also knows how the training side looks like

**- How do you currently get feedback from your training session participants?**
  - 2 ways:

      * either using online survey monkey links - get Elizabeth to send back report - often participants have no access to tech so didn't reach people (also pre-questionnaire),
      *  now back to paper-questionnaire to eliminate that uncertainty and tech accessibility problem in some places



**- How do you currently report the impact of your training sessions to the setting you work in?**

   - manually entering data into spreadsheets to process it 

## Tasks

- ### Task 1

  - [ ] To start off please can you register on the app to get to your dashboard.
    - also thinks that full name rather than username on register site would be better
    - no issues with the flow here   


- ### Task 2

  - [ ] Great. Now can you please visit the session held on the 3rd November and find out what your survey responders found most useful from that session's training.
    - go via sessions or results? unclear to user
    - results summary or overall results, results dashboard would fit better
    - the session type is fine 
    - unique URL instead of unique ID makes sense
    - gather personalized results would be interesting 
    - ranking session results (session details) by number of votes would be useful

- ### Task 3

  - [ ] Please, can you see their individual survey response you have received for this session?

    - no issues here

- ### Task 4

  - [ ] Now we would like you to view a summary of the results across all your sessions and see the feedback from your participants to the questions 'how important is it for you to support somebody with their mental health and wellbeing'
    - make entire question block clickable would make sense
    

- ### Task 5

  - [ ] Please, can you now add a new training session that you have coming up? 
     - number of attendants often unclear before sessions so maybe not very useful
     - maximum 16-18 suggested to the organization, the organization pays for training so participants get training for free, few incentives so drop out rates are quite high
     -  identifying drop out rates would be useful
    
- ### Task 6

  - [ ] Great please finally delete the session of the 3rd November
    - no issues here

## Follow Up Questions

**- How did you find using the application?**

  - good, clean, easy

**- Did you have any other observations that you’d like to share?**

   -  the way of booking people onto session would make sense like Eventbrite including all admin flows of a cms

**- Knowing what the platform is looking to do, is there anything else you would want to make you use it?**

  - biggest difficulty: access to the app for trainers but web-app might be still useful so they can use own devices and don't need to download anything
   - post survey eval most efficient because people do it on the spot using pen and paper which might link to some problems
  - paper survey disadvantage: having to hand it back directly to the trainer might trigger dishonest responses
   - free text comments are often the most useful/ best form of feedback for trainers
   - the app would be useful for the on-the-spot Connect 5 connector-trainer feedback session
