### ISSUE TITLE
User Journey: As a trainer, I would like to know and measure the impact of my training sessions

### ISSUE THREAD

**Issue by RamyAlshurafa** [yalla-coop/connect5#24]
### Acceptance criteria:
- [ ] On the landing page, As a trainer, I can select that I'm a trainer to find out more about the platform or select to find out more about the Connect 5 programme.
- [ ] As a trainer I can choose to log in or sign up on the Connect 5 platform.
- [ ] As a trainer I can sign up for the connect 5 platforms.
- [ ] As a trainer, I want to login to Connect 5 platform.
- [ ] As a trainer I want to get a dashboard on the platform, So I can get some actions.
- [ ] As a trainer I want to view all sessions that belong to me, so I can choose one of them to view in a separated page.
- [ ] As a trainer I want to view my sessions in a single page, so I can get more info about it.
- [ ] As a trainer I want to see the individual responses for the session I am looking at.
- [ ] As a user I want to delete a session I have created.
- [ ] As a trainer I want to view a summary of the results from all the sessions I have led.
- [ ] As a trainer I want a form to create a new session and fill the session information.
- [ ] As a trainer who has submitted a new session, I want to see that this has been successful and to immediately see the individual page for this session.
