### ISSUE TITLE
As a trainer I want to view a summary of the results from all the sessions I have led.

### ISSUE THREAD

**Issue by RamyAlshurafa** [yalla-coop/connect5#36]
## As a trainer I want to view a summary of the results from all the sessions I have led.
Relates #24 
 #### Acceptance criteria:
- [ ] When I'm on "Results" page, I would like to get statistics section which has two tabs:
  - [ ] Attendance tab: which contain statistics for the attendance numbers for each session.
  - [ ] Survey replies tab: which contains statistics for replies number for each session.
- [ ] When I'm on "Results" page, I would like to be able to navigate through attendance and replies tabs.
- [ ] When I'm on "Results" page, I would like to get questions list, not includes the inputs field questions[ id, region, trainer, ...] (just for ratable) questions
- [ ] When I'm on "Results" page, Iwould like to be able to click on any question and get a popup modal with the question details:
  - [ ] the question content.
  - [ ] question average rate for each question, with rate bar.
  - [ ] close button to close the popup modal and return back to results page view.
