### ISSUE TITLE
Survey Answer Flow Update

### ISSUE THREAD

**Issue by dupreesi** [yalla-coop/connect5#520]
**Updates general user flow**
> relates #521

- [x] - current question (e.g. image 1: What is your age) will be screen-centred and highlighted
- [x] - Once the user interacts and answers the app will automatically scroll down to the next question
- [x] - user won’t be able to answer any other questions (e.g. image 1: What is your gender) until they answered the highlighted question
- [x] - We show the next questions but fade it out to show the questions coming up but making it clear which one they still need to answer
- [x] - Once a question is being answered a user can always scroll back up and edit the answer
- [x] - Once all questions rendered on the page are being answered the user can proceed to the next set of questions
- [x] - The footer bar labelled as Your Progress indicates the amount of sections/ answers needed to finish the survey
- [x] ![image](https://user-images.githubusercontent.com/23721486/64546211-841b9c80-d32a-11e9-838f-e7e7b8a138cc.png)
- [x] ![image](https://user-images.githubusercontent.com/23721486/64546192-7b2acb00-d32a-11e9-97aa-eda6df389a70.png)
- [x] ![image](https://user-images.githubusercontent.com/23721486/64546209-82ea6f80-d32a-11e9-9335-7b022a50af2f.png)
- [ ] 
- [x] **Updates demographics**
- [x] >relates #522
- [x] - usage of dropdown menu for questions with more possible answers than average (e.g. ethnicity) -> save space on page
- [ ] 
- [x] **Updates behavioural insights**
- [x] >relates #523
- [x] - render star based review system between 1-5 (strongly disagree to strongly agree) with no stars indicating that question has not been answered
- [x] - User cannot answer the next question before answering current one 
- [x] -  (like above app would scroll to next question but user can edit all previous answers by scrolling back up)
